# Generated by Django 5.2.6 on 2025-10-10 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicbill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 10, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicbill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labbill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 10, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labbill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='materialpurchasebill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 10, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialpurchasebill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 10, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
