# Generated by Django 5.2.6 on 2025-10-21 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('billing', '0003_medicine_created_at_medicine_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='admin_panel.clinic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedure',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='admin_panel.clinic'),
            preserve_default=False,
        ),
    ]
