# Generated by Django 5.2.6 on 2025-12-18 08:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_medicine_clinic_procedure_clinic'),
        ('clinic_panel', '0007_patient_unique_file_number_per_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='labbill',
            name='clinic_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount charged to patient by clinic', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labbill',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='labbill',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_bills', to='clinic_panel.doctor'),
        ),
        migrations.AddField(
            model_name='labbill',
            name='file_number',
            field=models.CharField(default='N/A', help_text='Patient file number', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labbill',
            name='invoice_number',
            field=models.CharField(default='NA', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labbill',
            name='lab_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost charged by lab', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labbill',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_bills', to='clinic_panel.patient'),
        ),
        migrations.AddField(
            model_name='labbill',
            name='patient_name',
            field=models.CharField(default='UNKNOWN', help_text='Patient name (snapshot)', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LabBillItem',
        ),
    ]
