# Generated by Django 5.2.6 on 2025-12-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='file_number_start',
            field=models.PositiveIntegerField(default=6000, help_text='Starting file number for patients'),
        ),
    ]
