# Generated by Django 5.2.6 on 2025-10-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN', 'Admin'), ('CLINIC', 'Clinic'), ('DOCTOR', 'Doctor')], max_length=10),
        ),
    ]
