# Generated by Django 5.2.6 on 2025-09-12 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('pulse', models.CharField(blank=True, max_length=10, null=True)),
                ('respiratory_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('spo2', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('bmi', models.CharField(blank=True, max_length=10, null=True)),
                ('waist', models.CharField(blank=True, max_length=10, null=True)),
                ('complaints', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('advices', models.TextField(blank=True, null=True)),
                ('investigations', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, help_text='Mention any drug/food/environmental allergies', null=True)),
                ('next_consultation', models.DateField(blank=True, null=True)),
                ('empty_stomach_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='clinic_panel.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_panel.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_panel.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('1-0-0', '1-0-0 (Morning only)'), ('0-1-0', '0-1-0 (Afternoon only)'), ('0-0-1', '0-0-1 (Night only)'), ('1-0-1', '1-0-1 (Morning & Night)'), ('1-1-1', '1-1-1 (Morning, Afternoon & Night)'), ('0-1-1', '0-1-1 (Afternoon & Night)'), ('1-1-0', '1-1-0 (Morning & Afternoon)')], max_length=10)),
                ('duration', models.CharField(max_length=50)),
                ('timings', models.CharField(choices=[('BEFORE_MEAL', 'Before Meal'), ('AFTER_MEAL', 'After Meal'), ('ANYTIME', 'Anytime')], max_length=20)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor_panel.consultation')),
            ],
        ),
    ]
