# Generated by Django 5.2.6 on 2025-10-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_panel', '0002_prescription_created_at_prescription_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='heart_rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
