# Generated by Django 5.2.6 on 2025-10-16 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_medicine_created_at_medicine_updated_at_and_more'),
        ('doctor_panel', '0003_consultation_blood_pressure_consultation_heart_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.procedure'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, choices=[('1-0-0', '1-0-0 (Morning only)'), ('0-1-0', '0-1-0 (Afternoon only)'), ('0-0-1', '0-0-1 (Night only)'), ('1-0-1', '1-0-1 (Morning & Night)'), ('1-1-1', '1-1-1 (Morning, Afternoon & Night)'), ('0-1-1', '0-1-1 (Afternoon & Night)'), ('1-1-0', '1-1-0 (Morning & Afternoon)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='timings',
            field=models.CharField(blank=True, choices=[('BEFORE_MEAL', 'Before Meal'), ('AFTER_MEAL', 'After Meal'), ('ANYTIME', 'Anytime')], max_length=20, null=True),
        ),
    ]
