# Generated by Django 5.2.6 on 2025-12-18 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_panel', '0007_patient_unique_file_number_per_clinic'),
        ('doctor_panel', '0004_prescription_procedure_alter_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='findings',
            field=models.TextField(blank=True, help_text='Clinical findings / observations', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='referral_notes',
            field=models.TextField(blank=True, help_text='Reason for referral', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='referred_to',
            field=models.ForeignKey(blank=True, help_text='Referred doctor if patient is referred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_consultations', to='clinic_panel.doctor'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='treatment_done',
            field=models.TextField(blank=True, help_text='Treatment actually performed', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='treatment_plan',
            field=models.TextField(blank=True, help_text='Planned treatment approach', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='allergies',
            field=models.TextField(blank=True, help_text='Drug / food / environmental allergies', null=True),
        ),
    ]
