# Generated by Django 5.2.6 on 2025-09-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
