# Generated by Django 5.2.6 on 2025-10-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_panel', '0003_alter_doctor_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='patient_files/'),
        ),
    ]
