# Generated by Django 5.2.6 on 2025-12-18 05:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_panel', '0004_patient_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='patient',
            name='daily_medication',
            field=models.TextField(blank=True, help_text='Current daily medications', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='drug_allergy',
            field=models.TextField(blank=True, help_text='Drug allergy if any', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='file_number',
            field=models.CharField(blank=True, help_text='Patient File Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian_name',
            field=models.CharField(blank=True, help_text="Father's / Wife's / Husband's Name", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, help_text="Patient's Occupation", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='relationship_with_patient',
            field=models.CharField(blank=True, help_text='Relationship with patient', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='relative_name',
            field=models.CharField(blank=True, help_text='Name of Relative', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='PatientAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='patient_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='clinic_panel.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
