# Generated by Django 5.2.6 on 2025-12-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_clinic_file_number_start'),
        ('clinic_panel', '0006_patient_created_at_patient_updated_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('clinic', 'file_number'), name='unique_file_number_per_clinic'),
        ),
    ]
